import React from 'react';
import {
    InspectionRequest, Client, Car, CarMake, CarModel, InspectionType,
    Broker, CustomFindingCategory, PredefinedFinding, Settings, Employee,
    SettingsPage, Notification, ConfirmModalState, Permission, Page, AppNotification,
    Expense, Revenue, ActivityLog, InternalMessage, Technician,
    FinancialStats, ArchiveResult, PayrollDraft, Reservation
} from '../types';

export interface CarHistoryResult {
    car: Car;
    previousRequests: InspectionRequest[];
    lastClient?: Client;
}

export interface AppContextType {
    theme: 'light' | 'dark';
    toggleTheme: () => void;
    themeSetting: 'light' | 'dark' | 'system';
    setThemeSetting: (theme: 'light' | 'dark' | 'system') => void;
    page: Page;
    setPage: (page: Page) => void;
    goBack: () => void;
    settingsPage: SettingsPage;
    setSettingsPage: (page: SettingsPage) => void;
    requests: InspectionRequest[];
    loadMoreRequests: () => Promise<void>;
    hasMoreRequests: boolean;
    isLoadingMore: boolean;
    searchRequestByNumber: (query: string | number) => Promise<void>;
    clearSearchedRequests: () => void;
    searchedRequests: InspectionRequest[] | null;
    clients: Client[];
    selectedClientId: string | null;
    setSelectedClientId: (id: string | null) => void;
    cars: Car[];
    carMakes: CarMake[];
    carModels: CarModel[];
    fetchCarModelsByMake: (makeId: string) => Promise<void>;
    fetchCarMakes: () => Promise<void>;
    inspectionTypes: InspectionType[];
    brokers: Broker[];
    employees: Employee[];
    technicians: Technician[];
    expenses: Expense[];
    customFindingCategories: CustomFindingCategory[];
    predefinedFindings: PredefinedFinding[];
    selectedRequestId: string | null;
    setSelectedRequestId: (id: string | null) => void;
    authUser: Employee | null;
    setAuthUser: React.Dispatch<React.SetStateAction<Employee | null>>;
    login: (email: string, password: string) => Promise<{ success: boolean; error?: string }>;
    logout: () => void;
    updateOwnPassword: (newPassword: string) => Promise<void>;
    settings: Settings;
    updateSettings: (newSettings: Partial<Settings>) => Promise<void>;
    addRequest: (request: Omit<InspectionRequest, 'request_number'>) => Promise<InspectionRequest>;
    updateRequest: (updatedRequest: Partial<InspectionRequest> & { id: string }) => Promise<void>;
    fetchAndUpdateSingleRequest: (requestId: string) => Promise<void>;
    fetchRequestTabContent: (requestId: string, group: 'general' | 'categories' | 'gallery') => Promise<void>;
    fetchFullRequestForSave: (requestId: string) => Promise<InspectionRequest | null>;
    updateRequestAndAssociatedData: (payload: {
        originalRequest: InspectionRequest;
        formData: {
            client_id: string;
            car: Partial<Omit<Car, 'id'>>;
            request: Partial<Omit<InspectionRequest, 'id' | 'client_id' | 'car_id' | 'broker'>> & { broker: { id: string; commission: number; } | null; };
        };
    }) => Promise<void>;
    deleteRequest: (id: string) => Promise<void>;
    deleteRequestsBatch: (ids: string[]) => Promise<void>;
    addClient: (client: Client) => Promise<Client>;
    updateClient: (client: Client) => Promise<void>;
    deleteClient: (id: string) => Promise<void>;
    ensureLocalClient: (client: Client) => void;
    addCar: (car: Car) => Promise<Car>;
    uploadImage: (file: File, bucket: string) => Promise<string>;
    deleteImage: (imageUrl: string) => Promise<void>;
    addInspectionType: (type: Omit<InspectionType, 'id'>) => Promise<void>;
    updateInspectionType: (type: InspectionType) => Promise<void>;
    deleteInspectionType: (id: string) => Promise<void>;
    addFindingCategory: (category: Omit<CustomFindingCategory, 'id'>) => Promise<void>;
    updateFindingCategory: (category: CustomFindingCategory) => Promise<void>;
    deleteFindingCategory: (id: string) => Promise<void>;
    addPredefinedFinding: (finding: Omit<PredefinedFinding, 'id'>) => Promise<void>;
    updatePredefinedFinding: (finding: PredefinedFinding) => Promise<void>;
    deletePredefinedFinding: (id: string) => Promise<void>;
    addCarMake: (make: Omit<CarMake, 'id'>) => Promise<CarMake>;
    addCarMakesBulk: (makes: Omit<CarMake, 'id'>[]) => Promise<void>;
    updateCarMake: (make: CarMake) => Promise<void>;
    deleteCarMake: (id: string) => Promise<void>;
    deleteAllCarMakes: () => Promise<void>;
    addCarModel: (model: Omit<CarModel, 'id'>) => Promise<CarModel>;
    addCarModelsBulk: (models: Omit<CarModel, 'id'>[]) => Promise<void>;
    updateCarModel: (model: CarModel) => Promise<void>;
    deleteCarModel: (id: string) => Promise<void>;
    deleteModelsByMakeId: (makeId: string) => Promise<void>;
    addBroker: (broker: Omit<Broker, 'id'>) => Promise<Broker>;
    updateBroker: (broker: Broker) => Promise<void>;
    deleteBroker: (id: string) => Promise<void>;
    addTechnician: (tech: Omit<Technician, 'id'>) => Promise<Technician>;
    updateTechnician: (tech: Technician) => Promise<void>;
    deleteTechnician: (id: string) => Promise<void>;
    addEmployee: (employeeData: Omit<Employee, 'id'>) => Promise<Employee | undefined>;
    updateEmployee: (employee: Pick<Employee, 'id'> & Partial<Omit<Employee, 'id'>> & { resetPassword?: boolean }) => Promise<Employee | undefined>;
    adminChangePassword: (userId: string, newPassword: string) => Promise<void>;
    deleteEmployee: (id: string) => Promise<void>;
    addExpense: (expense: Omit<Expense, 'id'>) => Promise<void>;
    updateExpense: (expense: Expense) => Promise<void>;
    deleteExpense: (id: string) => Promise<void>;
    addRevenue: (revenue: Omit<Revenue, 'id'>) => Promise<void>;
    deleteRevenue: (id: string) => Promise<void>;
    notifications: Notification[];
    addNotification: (notification: Omit<Notification, 'id'>) => void;
    removeNotification: (id: string) => void;
    appNotifications: AppNotification[];
    markNotificationAsRead: (id: string) => void;
    markAllNotificationsAsRead: () => void;
    confirmModalState: ConfirmModalState;
    showConfirmModal: (modalState: Omit<ConfirmModalState, 'isOpen'>) => void;
    hideConfirmModal: () => void;
    isLoading: boolean;
    isRefreshing: boolean;
    isSetupComplete: boolean;
    startSetupProcess: () => void;
    can: (permission: Permission) => boolean;
    findOrCreateCarMake: (name: string) => Promise<CarMake>;
    findOrCreateCarModel: (name: string, makeId: string) => Promise<CarModel>;
    initialRequestModalState: 'new' | null;
    setInitialRequestModalState: (state: 'new' | null) => void;
    currentDbUsage: number;
    currentStorageUsage: number;
    newRequestSuccessState: { isOpen: boolean; requestNumber: number | null; requestId: string | null; };
    showNewRequestSuccessModal: (requestId: string | null, requestNumber: number | null) => void;
    hideNewRequestSuccessModal: () => void;
    shouldPrintDraft: boolean;
    setShouldPrintDraft: (shouldPrint: boolean) => void;
    fetchFinancialsData: (filter: 'today' | 'week' | 'month' | 'year') => Promise<{ requests: InspectionRequest[], expenses: Expense[] }>;
    createActivityLog: (action: string, details: string, imageUrl?: string, link_id?: string, link_page?: Page) => ActivityLog | null;
    systemLogs: ActivityLog[];
    searchClients: (query: string) => Promise<Client[]>;
    searchCars: (query: string) => Promise<Car[]>;
    searchCarMakes: (query: string) => Promise<CarMake[]>;
    searchCarModels: (makeId: string, query: string) => Promise<CarModel[]>;
    searchClientsPage: (page: number, pageSize: number, query?: string) => Promise<{ data: Client[], count: number }>;
    fetchClientRequests: (clientId: string) => Promise<InspectionRequest[]>;
    fetchClientRequestsFiltered: (clientId: string, startDate?: string, endDate?: string, onlyUnpaid?: boolean) => Promise<InspectionRequest[]>;
    getClientFinancialSummary: (clientId: string) => Promise<any[]>;
    fetchRequestsByCarId: (carId: string) => Promise<InspectionRequest[]>;
    fetchRequestByRequestNumber: (reqNum: number) => Promise<InspectionRequest | null>;
    fetchRequestByRequestNumberForAuth: (reqNum: number) => Promise<InspectionRequest | null>;
    fetchRequestsByDateRange: (startDate: string, endDate: string) => Promise<InspectionRequest[]>;
    checkCarHistory: (plateNumber: string | null, vin: string | null) => Promise<CarHistoryResult | null>;
    isOnline: boolean;
    realtimeStatus: 'connected' | 'connecting' | 'disconnected';
    retryConnection: () => void;
    refreshSessionAndReload: () => void;
    highlightedRequestId: string | null;
    triggerHighlight: (requestId: string) => void;
    unreadMessagesCount: number;
    fetchInboxMessages: () => Promise<InternalMessage[]>;
    fetchSentMessages: () => Promise<InternalMessage[]>;
    sendInternalMessage: (message: Omit<InternalMessage, 'id' | 'created_at' | 'sender_id' | 'sender_name' | 'is_read'>) => Promise<void>;
    markMessageAsRead: (id: string) => void;
    isFocusMode: boolean;
    setIsFocusMode: (isFocus: boolean) => void;
    hasUnsavedChanges: boolean;
    setHasUnsavedChanges: (hasChanges: boolean) => void;
    isMailboxOpen: boolean;
    setIsMailboxOpen: (isOpen: boolean) => void;
    searchArchive: (params: { startDate: string; endDate: string; query?: string }) => Promise<string[]>;
    expandedArchiveCarId: string | null;
    setExpandedArchiveCarId: (id: string | null) => void;
    deferredPrompt: any;
    installPwa: () => Promise<void>;
    factoryResetOperations: () => Promise<void>;
    factoryResetFull: () => Promise<void>;
    fetchServerFinancials: (startDate: string, endDate: string, includeCompletedOnly: boolean) => Promise<FinancialStats>;
    fetchServerExpenses: (startDate: string, endDate: string) => Promise<Expense[]>;
    fetchServerRevenues: (startDate: string, endDate: string) => Promise<Revenue[]>;
    fetchArchiveData: (startDate: string, endDate: string, query?: string) => Promise<ArchiveResult[]>;
    // --- Payroll ---
    fetchPayrollDraft: (month: number, year: number) => Promise<PayrollDraft | null>;
    savePayrollDraft: (draft: PayrollDraft) => Promise<void>;
    checkIfEmployeePaidThisMonth: (employeeId: string, month: number, year: number) => Promise<boolean>;
    fetchEmployeeTransactionsForMonth: (employeeId: string, month: number, year: number) => Promise<Expense[]>;
    isSessionError: boolean;
    incomingRequest: InspectionRequest | null;
    setIncomingRequest: React.Dispatch<React.SetStateAction<InspectionRequest | null>>;
    // --- Reservations ---
    reservations: Reservation[];
    fetchReservations: () => Promise<void>;
    addReservation: (reservation: Omit<Reservation, 'id' | 'created_at' | 'status'>) => Promise<void>;
    updateReservationStatus: (id: string, status: 'new' | 'confirmed' | 'converted' | 'cancelled') => Promise<void>;
    updateReservation: (id: string, data: Partial<Omit<Reservation, 'id' | 'created_at'>>) => Promise<void>;
    deleteReservation: (id: string) => Promise<void>;
    parseReservationText: (text: string) => Promise<Partial<Reservation>>;
    // --- Remote Deletion Event ---
    lastRemoteDeleteId: string | null;
    setLastRemoteDeleteId: (id: string | null) => void;
}
